#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev || mkdir /dev

# Создаём консоль и null
[ -c /dev/console ] || mknod /dev/console c 5 1
[ -c /dev/null ] || mknod /dev/null c 1 3
[ -c /dev/tty ] || mknod /dev/tty c 5 0

echo "=== Welcome to FreedomUI shell ==="

# Запуск шелла с консолью
while true; do
    /bin/sh -i < /dev/console > /dev/console 2>&1
done


